export default {
  user: [],
  register: [],
  component: 'index',
  userList: [],
  changeStatus: [],
  soundList: [],
  page: 'main',
  type: [],
  feeling: [],
  add_sound: 0,
  update_sound: 0,
  delete_sound: 0,
  get_sound: [],
  sound_analysis: [],
}
